import pandas

pandas.read_csv("B1.csv")
pandas.read_csv("D1.csv")
pandas.read_csv("D2.csv")
pandas.read_csv("E0.csv")
pandas.read_csv("E1.csv")
pandas.read_csv("E2.csv")
pandas.read_csv("E3.csv")
pandas.read_csv("EC.csv")
pandas.read_csv("F1.csv")
pandas.read_csv("F2.csv")
pandas.read_csv("G1.csv")
pandas.read_csv("I1.csv")
pandas.read_csv("I2.csv")
pandas.read_csv("N1.csv")
pandas.read_csv("P1.csv")
pandas.read_csv("SC0.csv")
pandas.read_csv("SC1.csv")
pandas.read_csv("SC2.csv")
pandas.read_csv("SC3.csv")
pandas.read_csv("SP1.csv")
pandas.read_csv("SP2.csv")
pandas.read_csv("T1.csv")