import pandas

pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/B1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/D1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/D2.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/E0.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/E1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/E2.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/E3.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/EC.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/F1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/F2.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/G1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/I1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/I2.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/N1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/P1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/SC0.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/SC1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/SC2.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/SC3.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/SP1.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/SP2.csv")
pandas.read_csv("C:/Users/Thoma/Documents/Professionnel/Cours/Gestion de Projet/T1.csv")